# Professional DPatch Training Configuration
# This configuration demonstrates how to use the new batch training system

# Attack configuration
attack_losses: 
  - "loss_classifier"
  - "loss_box_reg" 
  - "loss_objectness"
  - "loss_rpn_box_reg"

# Hardware configuration
cuda_visible_devices: "0"  # Use GPU 0, set to null for CPU

# Professional training parameters
max_epochs: 10              # 10 Number of training epochs
batch_size: 16              # 16 Batch size - adjust based on GPU memory
shuffle: true               # true Shuffle dataset for better training
max_training_images: 64  # null for all images, or specify number like 1000
random_seed: 42             # For reproducible results
save_interval: 5            # Save loss history every N batches
resume: false               # Resume from previous training

# Image processing
image_size: [200, 200]      # Target image size (height, width)

# training input parameters
# annotation_path: "dataset/vehicle_coco2017/annotations/instances_vehicle_train2017.json"
# image_directory: "dataset/vehicle_coco2017/images/train2017"
training_annotation_path: "dataset/vehicle_images_5/annotations/vehicle_5_per_class.json"
training_image_directory: "dataset/vehicle_images_5/images"
config_file: "mmdetection/configs/faster_rcnn/faster-rcnn_r101_fpn_1x_coco-dpatch.py"
checkpoint_file: "mmdetection/weights/faster_rcnn_r101_fpn_1x_coco.pth"

# training output parameters
training_output_dir: "results/dpatch_fasterrcnn/training_output"
training_visualization_dir: "results/dpatch_fasterrcnn/training_output/visualization"
training_images_save_dir: "results/dpatch_fasterrcnn/training_output/images"
training_comparison_dir: "results/dpatch_fasterrcnn/training_output/comparison"
training_log_dir: "results/dpatch_fasterrcnn/training_output/log"
training_patch_dir: "results/dpatch_fasterrcnn/training_output/patch"

# test parameters
test_image_file: "dataset/vehicle_images_5/images/000000000471.jpg"  # For testing
test_annotation_path: "dataset/vehicle_images_5/annotations/vehicle_5_per_class.json"
test_output_dir: "results/dpatch_fasterrcnn/test_output"

# Advanced options (commented out)
# crop_range: [0, 0]
# brightness_range: [1.0, 1.0] 
# rotation_weights: [1, 0, 0, 0]
# sample_size: 1 